export interface Article {
  slug: string;
  category: string;
  filterTag: 'ai-strategy' | 'design-leadership' | 'business-roi' | 'soft-skills' | 'ai-ethics' | 'ops-strategy';
  title: string;
  subtitle: string;
  date: string;
  readingTime: string;
  summary: string;
  patternClass: string;
  featured?: boolean;
}

export const articles: Article[] = [
  {
    slug: "roi-of-experience",
    category: "Business Strategy",
    filterTag: "business-roi",
    title: "Beyond Vanity Metrics: The ROI of Experience in 2026",
    subtitle: "If you are reporting NPS in a budget meeting, you've already lost the room.",
    date: "Jan 20, 2026",
    readingTime: "4 min read",
    summary: "Strategic design is no longer about how the user feels, but about how fast the organization moves.",
    patternClass: "pattern-systems",
    featured: true,
  },
  {
    slug: "ai-leadership-paradox",
    category: "AI / Leadership",
    filterTag: "ai-strategy",
    title: "The AI Paradox: High-Tech Demands High-Touch Leadership",
    subtitle: "AI generates answers; leaders generate the right questions.",
    date: "Jan 25, 2026",
    readingTime: "5 min read",
    summary: "As AI commoditizes execution, the value of a 'Maker' shifts toward the 'Director'.",
    patternClass: "pattern-ai",
    featured: false,
  },
  {
    slug: "authority-gap",
    category: "Executive Presence",
    filterTag: "design-leadership",
    title: "The Authority Gap: Why Your Title Isn't Enough",
    subtitle: "Shifting from 'Design Evangelist' to 'Strategic Architect'.",
    date: "Jan 30, 2026",
    readingTime: "4 min read",
    summary: "Authority in 2026 isn't granted by a seat at the table; it's earned by solving expensive problems.",
    patternClass: "pattern-leadership",
    featured: false,
  },
  {
    slug: "outcome-stories",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "Outcome Stories: Measuring Design Impact That Matters",
    subtitle: "Stop counting deliverables. Start counting decisions influenced.",
    date: "Feb 5, 2026",
    readingTime: "6 min read",
    summary: "The most powerful design metric isn't pixels shipped. It's organizational behavior changed.",
    patternClass: "pattern-outcomes",
    featured: true,
  },
  {
    slug: "lean-leadership",
    category: "Soft Skills",
    filterTag: "soft-skills",
    title: "Lean Leadership: The Art of Doing Less, Better",
    subtitle: "Efficiency isn't about speed. It's about eliminating waste.",
    date: "Feb 10, 2026",
    readingTime: "5 min read",
    summary: "High-performing design teams don't work harder. They work on fewer, better things.",
    patternClass: "pattern-lean",
    featured: false,
  },
  {
    slug: "ai-guardrails",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "AI Guardrails: Building Trust at Scale",
    subtitle: "Users don't want magical AI. They want predictable AI.",
    date: "Feb 15, 2026",
    readingTime: "7 min read",
    summary: "The difference between delightful and dangerous AI is a well-designed constraint system.",
    patternClass: "pattern-guardrails",
    featured: false,
  },
  {
    slug: "strategy-bottleneck",
    category: "AI Ethics",
    filterTag: "ai-ethics",
    title: "The Strategy Bottleneck: Why 'Can AI do it?' is the Wrong Question",
    subtitle: "When generative speed replaces strategic friction, we stop solving problems and start just picking options.",
    date: "Feb 20, 2026",
    readingTime: "4 min read",
    summary: "As leaders, our role is to reintroduce Strategic Friction.",
    patternClass: "pattern-bottleneck",
    featured: false,
  },
  {
    slug: "research-inflection",
    category: "Ops Strategy",
    filterTag: "ops-strategy",
    title: "The Research Inflection Point: The End of Manual Analysis",
    subtitle: "Jakob Nielsen's 2026 findings are clear: AI is now a better observer of user emotion than a junior researcher.",
    date: "Feb 25, 2026",
    readingTime: "5 min read",
    summary: "We aren't automating empathy; we are automating observation.",
    patternClass: "pattern-research",
    featured: false,
  },
  {
    slug: "generalist-advantage",
    category: "Talent Strategy",
    filterTag: "soft-skills",
    title: "The Return of the Generalist: Why Depth is Dead",
    subtitle: "In an AI world, specialized execution is a commodity. Synthesis is the new premium.",
    date: "Mar 1, 2026",
    readingTime: "5 min read",
    summary: "Don't polish the pixel; orchestrate the system.",
    patternClass: "pattern-generalist",
    featured: false,
  },
  {
    slug: "design-debt",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "Design Debt is Strategy Debt",
    subtitle: "A confused product doesn't have a visual problem. It has accumulated decisions without coherence.",
    date: "Mar 5, 2026",
    readingTime: "5 min read",
    summary: "Inconsistency is a leadership failure, not a design failure. Here's what it actually costs.",
    patternClass: "pattern-systems",
    featured: false,
  },
  {
    slug: "trust-layer",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "The Trust Layer: Designing Human-AI Collaboration",
    subtitle: "The interface is a promise. In AI products, it's a promise you can't afford to break.",
    date: "Mar 10, 2026",
    readingTime: "5 min read",
    summary: "Good AI products don't impress users. They reassure them. The trust layer is the product.",
    patternClass: "pattern-ai",
    featured: true,
  },
  {
    slug: "ambassador-model",
    category: "Ops Strategy",
    filterTag: "ops-strategy",
    title: "The Ambassador Model: Scaling Design Culture Without Headcount",
    subtitle: "You can't hire your way to a design culture. You have to grow it from inside.",
    date: "Mar 15, 2026",
    readingTime: "5 min read",
    summary: "How 125+ non-designers became BBVA Colombia's most powerful design asset.",
    patternClass: "pattern-leadership",
    featured: false,
  },
  {
    slug: "order-taker",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "From Order-Taker to Decision-Maker",
    subtitle: "Influence isn't given at the table. It's built before you enter the room.",
    date: "Mar 20, 2026",
    readingTime: "5 min read",
    summary: "The move from execution to strategy doesn't start with a promotion. It starts with how you frame problems.",
    patternClass: "pattern-outcomes",
    featured: false,
  },
  {
    slug: "cost-of-confusion",
    category: "Business ROI",
    filterTag: "business-roi",
    title: "The Real Cost of a Confused Product",
    subtitle: "Inconsistency isn't an aesthetic problem. It's a revenue problem.",
    date: "Mar 25, 2026",
    readingTime: "6 min read",
    summary: "Support volume, abandonment, rework, brand erosion: product confusion has a price. Here's how to calculate it.",
    patternClass: "pattern-bottleneck",
    featured: false,
  },
  {
    slug: "hire-for-judgment",
    category: "Talent Strategy",
    filterTag: "soft-skills",
    title: "Hire for Judgment, Not for Tools",
    subtitle: "In an AI world, the designer who knows Figma best is the least defensible hire you can make.",
    date: "Apr 1, 2026",
    readingTime: "5 min read",
    summary: "We hired for execution and expected leadership. In 2026, those are different jobs.",
    patternClass: "pattern-generalist",
    featured: false,
  },
  {
    slug: "ai-harness",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "The Runaway Horse and How to Rein It In",
    subtitle: "Most teams spend 90% of their energy picking the model. Almost nothing goes into the environment around it.",
    date: "Apr 8, 2026",
    readingTime: "4 min read",
    summary: "The model hasn't changed. The harness changed everything. A primer on building the environment that makes AI agents predictable.",
    patternClass: "pattern-ai",
    featured: false,
  },
  {
    slug: "ai-where-it-belongs",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "The Question Nobody Asks Before Adding AI to Their Product",
    subtitle: "Visible and valuable aren't the same thing. Most product teams never notice the difference.",
    date: "Apr 15, 2026",
    readingTime: "4 min read",
    summary: "A framework for deciding where AI actually belongs in your product, before you build it.",
    patternClass: "pattern-guardrails",
    featured: false,
  },
  {
    slug: "ai-trust-calibration",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "Why Your Users Don't Trust Your AI (Even When It Works)",
    subtitle: "Accuracy is necessary. It's not sufficient. The other two parts are where products fail.",
    date: "Apr 22, 2026",
    readingTime: "5 min read",
    summary: "Trust in an AI system has three components: competence, benevolence, and integrity. Most teams only design for one.",
    patternClass: "pattern-ai",
    featured: false,
  },
  {
    slug: "corrections-md",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "corrections.md: The Most Valuable File You're Not Keeping",
    subtitle: "AI agents don't have persistent memory. Your codebase can.",
    date: "Apr 29, 2026",
    readingTime: "4 min read",
    summary: "An append-only log of every agent mistake and correction. No measurable ROI on day one. By month three, it's the most valuable artifact in your codebase.",
    patternClass: "pattern-systems",
    featured: false,
  },
  {
    slug: "designer-trains-model",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "The Designer's New Job: Training the Model",
    subtitle: "When the feature is a model making decisions, the interface is the easy part.",
    date: "May 6, 2026",
    readingTime: "5 min read",
    summary: "The new design artifacts: DESIGN.md, voice.md, domain-patterns.md, trust calibration guidelines. And why the designer is the only one in the room thinking about the user as a human being.",
    patternClass: "pattern-leadership",
    featured: false,
  },
  {
    slug: "design-md",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "DESIGN.md: Making Your Design System Machine-Readable",
    subtitle: "The design system you built in Figma is invisible to the model writing your code. Here's the fix.",
    date: "May 13, 2026",
    readingTime: "4 min read",
    summary: "Semantic tokens, plain markdown, no plugins. How to make your design system legible to the AI agents building your product.",
    patternClass: "pattern-systems",
    featured: false,
  },
  {
    slug: "not-the-user",
    category: "Product Strategy",
    filterTag: "design-leadership",
    title: "Neither of Us Is the User",
    subtitle: "Before we build the AI feature everyone wants, six people who pay for the product get to tell us we're wrong.",
    date: "Jul 1, 2026",
    readingTime: "4 min read",
    summary: "An AI coach for The Birdie Club is weeks of work. Before it gets a budget, six members get a screen-shared session and four yes-or-no hypotheses get tested.",
    patternClass: "pattern-research",
    featured: false,
  },
  {
    slug: "builder-cant-see",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "The Builder Can't See the Gaps",
    subtitle: "Two AI reviewers read the same pull request. One approved it. The other found two blockers, and it was right.",
    date: "Aug 5, 2026",
    readingTime: "3 min read",
    summary: "When an AI writes most of the code, the session that built it is the worst judge of it. Why every spec'd change now goes through two reviewers from different model families.",
    patternClass: "pattern-guardrails",
    featured: false,
  },
  {
    slug: "five-members-four-hypotheses",
    category: "Product Strategy",
    filterTag: "business-roi",
    title: "Five Members, Four Hypotheses, One Feature on Hold",
    subtitle: "The research I promised in July. Most of our hypotheses were wrong, and the AI coach will wait.",
    date: "Aug 12, 2026",
    readingTime: "4 min read",
    summary: "Five screen-shared sessions with Birdie Club members. Nobody stayed for a feature, and five cheaper fixes moved ahead of the AI coach.",
    patternClass: "pattern-outcomes",
    featured: false,
  },
  {
    slug: "zero-is-not-a-pass",
    category: "Ops Strategy",
    filterTag: "ops-strategy",
    title: "A Zero Is Not a Pass",
    subtitle: "Failures get investigated by habit. The green checks are where bad measurements hide.",
    date: "Aug 19, 2026",
    readingTime: "3 min read",
    summary: "Four measurements in one day that looked fine and were wrong, all toward \"it works\". What I check now before a good result goes into a report.",
    patternClass: "pattern-lean",
    featured: false,
  },
  {
    slug: "guidelines-dont-enforce",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "Guidelines Don't Enforce Themselves",
    subtitle: "One project's instruction file reached 107,000 words. The failures got caught by two small scripts.",
    date: "Aug 26, 2026",
    readingTime: "3 min read",
    summary: "A rule in a document changed nothing; two small scripts caught real failures on day one. The same lesson applies to design system governance.",
    patternClass: "pattern-systems",
    featured: false,
  },
  {
    slug: "unused-skills",
    category: "Ops Strategy",
    filterTag: "ops-strategy",
    title: "573 of My AI Skills Had Never Run Once",
    subtitle: "Installing a capability feels like progress. For an AI agent, most of them are noise it has to read past.",
    date: "Sep 23, 2026",
    readingTime: "3 min read",
    summary: "A usage counter, a truncated list and two security audits that used none of the 26 security skills installed. Retiring tools by data, not memory.",
    patternClass: "pattern-lean",
    featured: false,
  },
  {
    slug: "cheap-options",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "Cheap Options, Expensive Choices",
    subtitle: "I built three full directions for this site in a day. The hard part was knowing why two of them had to lose.",
    date: "Sep 24, 2026",
    readingTime: "3 min read",
    summary: "AI raised the floor of what one person builds in a day. The calls that decided this redesign came from context the model didn't have.",
    patternClass: "pattern-ai",
    featured: false,
  },
  {
    slug: "rejected-options",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "Show the Options You Rejected",
    subtitle: "Why the case studies on this site are now decision records, and what the stricter format made me fix.",
    date: "Sep 25, 2026",
    readingTime: "3 min read",
    summary: "Borrowed from software architecture: context, options, decision, consequences. The rejected options are the evidence a hiring manager is looking for.",
    patternClass: "pattern-leadership",
    featured: false,
  },
];

export const filterOptions = [
  { value: "all", label: "All" },
  { value: "ai-strategy", label: "AI Strategy" },
  { value: "ai-ethics", label: "AI Ethics" },
  { value: "design-leadership", label: "Design Leadership" },
  { value: "business-roi", label: "Business ROI" },
  { value: "ops-strategy", label: "Ops Strategy" },
  { value: "soft-skills", label: "Soft Skills" },
] as const;

export type FilterValue = typeof filterOptions[number]['value'];
