export interface Article {
  slug: string;
  category: string;
  filterTag: 'ai-strategy' | 'design-leadership' | 'business-roi' | 'soft-skills' | 'ai-ethics' | 'ops-strategy';
  title: string;
  subtitle: string;
  date: string;
  readingTime: string;
  summary: string;
  patternClass: string;
  featured?: boolean;
}

export const articles: Article[] = [
  {
    slug: "roi-of-experience",
    category: "Business Strategy",
    filterTag: "business-roi",
    title: "Beyond Vanity Metrics: The ROI of Experience in 2026",
    subtitle: "If you are reporting NPS in a budget meeting, you've already lost the room.",
    date: "Jan 20, 2026",
    readingTime: "4 min read",
    summary: "Strategic design is no longer about how the user feels, but about how fast the organization moves.",
    patternClass: "pattern-systems",
    featured: true,
  },
  {
    slug: "ai-leadership-paradox",
    category: "AI / Leadership",
    filterTag: "ai-strategy",
    title: "The AI Paradox: High-Tech Demands High-Touch Leadership",
    subtitle: "AI generates answers; leaders generate the right questions.",
    date: "Jan 25, 2026",
    readingTime: "5 min read",
    summary: "As AI commoditizes execution, the value of a 'Maker' shifts toward the 'Director'.",
    patternClass: "pattern-ai",
    featured: false,
  },
  {
    slug: "authority-gap",
    category: "Executive Presence",
    filterTag: "design-leadership",
    title: "The Authority Gap: Why Your Title Isn't Enough",
    subtitle: "Shifting from 'Design Evangelist' to 'Strategic Architect'.",
    date: "Jan 30, 2026",
    readingTime: "4 min read",
    summary: "Authority in 2026 isn't granted by a seat at the table; it's earned by solving expensive problems.",
    patternClass: "pattern-leadership",
    featured: false,
  },
  {
    slug: "outcome-stories",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "Outcome Stories: Measuring Design Impact That Matters",
    subtitle: "Stop counting deliverables. Start counting decisions influenced.",
    date: "Feb 5, 2026",
    readingTime: "6 min read",
    summary: "The most powerful design metric isn't pixels shipped—it's organizational behavior changed.",
    patternClass: "pattern-outcomes",
    featured: true,
  },
  {
    slug: "lean-leadership",
    category: "Soft Skills",
    filterTag: "soft-skills",
    title: "Lean Leadership: The Art of Doing Less, Better",
    subtitle: "Efficiency isn't about speed—it's about eliminating waste.",
    date: "Feb 10, 2026",
    readingTime: "5 min read",
    summary: "High-performing design teams don't work harder. They work on fewer, better things.",
    patternClass: "pattern-lean",
    featured: false,
  },
  {
    slug: "ai-guardrails",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "AI Guardrails: Building Trust at Scale",
    subtitle: "Users don't want magical AI. They want predictable AI.",
    date: "Feb 15, 2026",
    readingTime: "7 min read",
    summary: "The difference between delightful and dangerous AI is a well-designed constraint system.",
    patternClass: "pattern-guardrails",
    featured: false,
  },
  {
    slug: "strategy-bottleneck",
    category: "AI Ethics",
    filterTag: "ai-ethics",
    title: "The Strategy Bottleneck: Why 'Can AI do it?' is the Wrong Question",
    subtitle: "When generative speed replaces strategic friction, we stop solving problems and start just picking options.",
    date: "Feb 20, 2026",
    readingTime: "4 min read",
    summary: "As leaders, our role is to reintroduce Strategic Friction.",
    patternClass: "pattern-bottleneck",
    featured: false,
  },
  {
    slug: "research-inflection",
    category: "Ops Strategy",
    filterTag: "ops-strategy",
    title: "The Research Inflection Point: The End of Manual Analysis",
    subtitle: "Jakob Nielsen's 2026 findings are clear: AI is now a better observer of user emotion than a junior researcher.",
    date: "Feb 25, 2026",
    readingTime: "5 min read",
    summary: "We aren't automating empathy; we are automating observation.",
    patternClass: "pattern-research",
    featured: false,
  },
  {
    slug: "generalist-advantage",
    category: "Talent Strategy",
    filterTag: "soft-skills",
    title: "The Return of the Generalist: Why Depth is Dead",
    subtitle: "In an AI world, specialized execution is a commodity. Synthesis is the new premium.",
    date: "Mar 1, 2026",
    readingTime: "5 min read",
    summary: "Don't polish the pixel; orchestrate the system.",
    patternClass: "pattern-generalist",
    featured: false,
  },
  {
    slug: "design-debt",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "Design Debt is Strategy Debt",
    subtitle: "A confused product doesn't have a visual problem. It has accumulated decisions without coherence.",
    date: "Mar 5, 2026",
    readingTime: "5 min read",
    summary: "Inconsistency is a leadership failure, not a design failure. Here's what it actually costs.",
    patternClass: "pattern-systems",
    featured: false,
  },
  {
    slug: "trust-layer",
    category: "AI Strategy",
    filterTag: "ai-strategy",
    title: "The Trust Layer: Designing Human-AI Collaboration",
    subtitle: "The interface is a promise. In AI products, it's a promise you can't afford to break.",
    date: "Mar 10, 2026",
    readingTime: "5 min read",
    summary: "Good AI products don't impress users — they reassure them. The trust layer is the product.",
    patternClass: "pattern-ai",
    featured: true,
  },
  {
    slug: "ambassador-model",
    category: "Ops Strategy",
    filterTag: "ops-strategy",
    title: "The Ambassador Model: Scaling Design Culture Without Headcount",
    subtitle: "You can't hire your way to a design culture. You have to grow it from inside.",
    date: "Mar 15, 2026",
    readingTime: "5 min read",
    summary: "How 125+ non-designers became BBVA Colombia's most powerful design asset.",
    patternClass: "pattern-leadership",
    featured: false,
  },
  {
    slug: "order-taker",
    category: "Design Leadership",
    filterTag: "design-leadership",
    title: "From Order-Taker to Decision-Maker",
    subtitle: "Influence isn't given at the table. It's built before you enter the room.",
    date: "Mar 20, 2026",
    readingTime: "5 min read",
    summary: "The move from execution to strategy doesn't start with a promotion. It starts with how you frame problems.",
    patternClass: "pattern-outcomes",
    featured: false,
  },
  {
    slug: "cost-of-confusion",
    category: "Business ROI",
    filterTag: "business-roi",
    title: "The Real Cost of a Confused Product",
    subtitle: "Inconsistency isn't an aesthetic problem. It's a revenue problem.",
    date: "Mar 25, 2026",
    readingTime: "6 min read",
    summary: "Support volume, abandonment, rework, brand erosion — product confusion has a price. Here's how to calculate it.",
    patternClass: "pattern-bottleneck",
    featured: false,
  },
  {
    slug: "hire-for-judgment",
    category: "Talent Strategy",
    filterTag: "soft-skills",
    title: "Hire for Judgment, Not for Tools",
    subtitle: "In an AI world, the designer who knows Figma best is the least defensible hire you can make.",
    date: "Apr 1, 2026",
    readingTime: "5 min read",
    summary: "We hired for execution and expected leadership. In 2026, those are different jobs.",
    patternClass: "pattern-generalist",
    featured: false,
  },
];

export const filterOptions = [
  { value: "all", label: "All" },
  { value: "ai-strategy", label: "AI Strategy" },
  { value: "ai-ethics", label: "AI Ethics" },
  { value: "design-leadership", label: "Design Leadership" },
  { value: "business-roi", label: "Business ROI" },
  { value: "ops-strategy", label: "Ops Strategy" },
  { value: "soft-skills", label: "Soft Skills" },
] as const;

export type FilterValue = typeof filterOptions[number]['value'];
